version: "3.7"
services:
  app:
    image: bresnow/remix-gun_dev:${VERSION:-0.0.16}
    volumes:
      - packages:/app/packages
      - config:/app/config
      - node_modules:/app/node_modules
      - public:/app/packages/remix/public
    environment:
      - STACK_NAME={{ index .Service.Labels "com.docker.stack.namespace" }}
      - RELAY_PORT=${RELAY_PORT:-3000}
      - PORT=${PORT:-3333}
    networks:
      - socket-proxy
      - edge
      - public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        - traefik.http.routers.remix-gun-app-${NUMBER:-0}.rule=Host(`${DOMAIN:-fltngmmth.com}`)
        - traefik.http.routers.remix-gun-app-${NUMBER:-0}.entrypoints=http,https
        - traefik.http.routers.remix-gun-app-${NUMBER:-0}.middlewares=https-redirect

        - traefik.http.routers.remix-gun-app-${NUMBER:-0}.tls.certresolver=dns
        - traefik.http.services.remix-gun-app-${NUMBER:-0}.loadbalancer.server.port=${PORT:-3333}
        # - traefik.http.services.remix-gun-app-${NUMBER:-0}.loadbalancer.passHostHeader=true

  chrome:
    image: jlesage/firefox
    # environment:
    #   - VNC_PASSWORD="Admin"
    # shm_size: '2gb'
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        - traefik.http.routers.chrome-${NUMBER:-0}.rule=Host(`${CDOMAIN:-chrome.fltngmmth.com}`)
        - traefik.http.routers.chrome-${NUMBER:-0}.entrypoints=http,https
        - traefik.http.routers.chrome-${NUMBER:-0}.middlewares=https-redirect

        - traefik.http.routers.chrome-${NUMBER:-0}.tls.certresolver=dns
        - traefik.http.services.chrome-${NUMBER:-0}.loadbalancer.server.port=5800
        # - traefik.http.services.chrome-${NUMBER:-0}.loadbalancer.passHostHeader=true
    networks:
      # - socket-proxy
      - edge
      - public
volumes:
  public:
    driver: local-persist
    driver_opts:
      mountpoint: ${PWD}/packages/remix/public
  packages:
    driver: local-persist
    driver_opts:
      mountpoint: ${PWD}/packages
  node_modules:
    driver: local-persist
    driver_opts:
      mountpoint: ${PWD}/node_modules
  config:
    driver: local-persist
    driver_opts:
      mountpoint: ${PWD}/config

networks:
  edge:
    external: true
  socket-proxy:
    external: true
  public:
    external: true
