version: "3.7"
services:
  app:
    image: bresnow/remix-gun_dev:${VERSION:-0.0.16}
    volumes:
      - packages:/app/packages
      - config:/app/config
      - node_modules:/app/node_modules
      - public:/app/packages/remix/public
    environment:
      - STACK_NAME={{ index .Service.Labels "com.docker.stack.namespace" }}
      - RELAY_PORT=${RELAY_PORT:-3000}
      - PORT=${PORT:-3333}
    networks:
      - socket-proxy
      - edge
      - public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        - traefik.http.routers.remix-gun-app-${NUMBER:-0}.rule=Host(`${DOMAIN:-remix-gun.fltngmmth.com}`)
        - traefik.http.routers.remix-gun-app-${NUMBER:-0}.entrypoints=http,https
        - traefik.http.routers.remix-gun-app-${NUMBER:-0}.middlewares=https-redirect
        - traefik.http.routers.remix-gun-app-${NUMBER:-0}.tls=true
        - traefik.http.routers.remix-gun-app-${NUMBER:-0}.tls.certresolver=le
        - traefik.http.services.remix-gun-app-${NUMBER:-0}.loadbalancer.server.port=${PORT:-3333}

  relay:
    image: nginx:1.17-alpine
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:80/ || exit 1
      interval: 3s
      timeout: 600s
      retries: 3
      start_period: 5s
    environment:
      - STACK_NAME={{ index .Service.Labels "com.docker.stack.namespace" }}
      - RELAY_PORT=${RELAY_PORT:-3000}
    networks:
      - edge
      - public
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        - traefik.http.routers.relay-${NUMBER:-0}.rule=Host(`${RELAY_SUBDOMAIN:-relay}.fltngmmth.com`)
        - traefik.http.routers.relay-${NUMBER:-0}.tls.certresolver=le
        - traefik.http.routers.relay-${NUMBER:-0}.entrypoints=http,https
        - traefik.http.services.relay-${NUMBER:-0}.loadbalancer.server.port=80
        - traefik.http.services.relay-${NUMBER:-0}.loadbalancer.passhostheader=true
        - traefik.http.services.relay-${NUMBER:-0}.loadbalancer.healthcheck.path=/healthcheck
        - traefik.http.services.relay-${NUMBER:-0}.loadbalancer.healthcheck.interval=100ms
        - traefik.http.services.relay-${NUMBER:-0}.loadbalancer.healthcheck.timeout=75ms
        - traefik.http.services.relay-${NUMBER:-0}.loadbalancer.healthcheck.scheme=http
      resources:
        limits:
          memory: 128MB

configs:
  nginx_config:
    name: nginx-config-${NGINX_CONFIG:-1}
    file: ${PWD}/config/nginx/nginx.relay.conf
volumes:
  public:
    driver: local-persist
    driver_opts:
      mountpoint: ${PWD}/packages/remix/public
  packages:
    driver: local-persist
    driver_opts:
      mountpoint: ${PWD}/packages
  node_modules:
    driver: local-persist
    driver_opts:
      mountpoint: ${PWD}/node_modules
  config:
    driver: local-persist
    driver_opts:
      mountpoint: ${PWD}/config

networks:
  edge:
    external: true
  socket-proxy:
    external: true
  public:
    external: true
