# DOMAIN=example.com docker stack deploy -c kanboard.yml kanboard
# php cli user:reset-password <username> # Change user password

version: '3.8'

services:
  kanboard:
    image: kanboard/kanboard:${VERSION:-v1.2.21}
    environment:
      - PLUGIN_INSTALLER=true
      - MAIL_TRANSPORT=${MAIL_TRANSPORT:-smtp}
      - MAIL_SMTP_HOSTNAME=${SMTP_HOST}
      - MAIL_SMTP_PORT=${SMTP_PORT:-587}
      - MAIL_SMTP_USERNAME=${SMTP_USERNAME}
      - MAIL_SMTP_PASSWORD=${SMTP_PASSWORD}
      - MAIL_SMTP_ENCRYPTION=${SMTP_ENCRYPTION}
    volumes:
      - ${VOLUME_PATH}data:/var/www/app/data
      - ${VOLUME_PATH}plugins:/var/www/app/plugins
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.kanboard-${NUMBER:-0}.rule=Host(`${DOMAIN:-kanboard.fltngmmth.com}`)
        - traefik.http.routers.kanboard-${NUMBER:-0}.entrypoints=http
        - traefik.http.routers.kanboard-${NUMBER:-0}.middlewares=https-redirect
        - traefik.http.routers.kanboard-${NUMBER:-0}-https.rule=Host(`${DOMAIN:-kanboard.fltngmmth.com}`)
        - traefik.http.routers.kanboard-${NUMBER:-0}-https.entrypoints=https
        - traefik.http.routers.kanboard-${NUMBER:-0}-https.service=kanboard-${NUMBER:-0}
        - traefik.http.routers.kanboard-${NUMBER:-0}-https.tls=true
        - traefik.http.routers.kanboard-${NUMBER:-0}-https.tls.certresolver=le
        - traefik.http.services.kanboard-${NUMBER:-0}.loadbalancer.server.port=80
    networks:
      - internal
      - traefik

volumes:
  data:
  plugins:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-public
